name: Cut release
on:
  workflow_dispatch:
    inputs:
      version_number:
        description: 'Version Number'
        required: true

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Run the tests
        run: yarn test
      - name: Build the release artifacts
        run: yarn build
      - name: Create the release
        run: yarn release
